

variables:

  LIBS_PREFIX: "s3://thetradedesk-mlplatform-us-east-1/libs/"

stages:
  - test
  - assembly_upload
  - deploy
  - k8s_deploy


####
## GitLab fails when using !reference inside workflow key thus the duplication here 
## * ignore scheduled triggers 
## * create pipelines for merge requests 
## * create pipelines for `master` branch commits. other branches are ignored. 
####
workflow:
  rules: 
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'

# TODO: build a default image with mvn, sbt, docker, etc - so we use one image for everything
default:
  # As global properties it's deprecated https://docs.gitlab.com/ee/ci/yaml/#globally-defined-image-services-cache-before_script-after_script
  cache:
    untracked: true
    paths:
      - "sbt-cache/ivy/cache"
      - "sbt-cache/boot"
      - "sbt-cache/sbtboot"
      - "sbt-cache/target"
      - "sbt-cache/coursier"

  before_script:
    #aws cli requires pip, which requires python, which the image does not have
    # Debian stretch got deprecated & moved to archive
    - echo 'deb http://archive.debian.org/debian stretch main' > /etc/apt/sources.list
   
    - apt-get update
    - apt-get install python3 -y
    - apt-get install python3-pip -y
    - export PATH=~/.local/bin:$PATH
    - pip3 install awscli # Install aws
    - apt-get install zip
    # creating a branch is needed for sbtrelease.Vcs. This is needed because gitlab
    # operates in "detached head" mode
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - echo "print all env variables"
    - env

# include all job ci files here:
include:
  - local: 'plutus/.gitlab-ci.yml'
  - local: 'contextual-features-scala/.gitlab-ci.yml'
  - local: 'benchmark-suite/.gitlab-ci.yml'
  - local: 'philo/.gitlab-ci.yml'
  - local: 'kongming/.gitlab-ci.yml'
  - local: 'audience/.gitlab-ci.yml'
