variables:

  LIBS_PREFIX: "s3://thetradedesk-mlplatform-us-east-1/libs/"

stages:
  - test
  - assembly_upload
  - deploy
  - k8s_deploy
 
# TODO: build a default image with mvn, sbt, docker, etc - so we use one image for everything
default:
  # As global properties it's deprecated https://docs.gitlab.com/ee/ci/yaml/#globally-defined-image-services-cache-before_script-after_script
  cache:
    untracked: true
    paths:
      - "sbt-cache/ivy/cache"
      - "sbt-cache/boot"
      - "sbt-cache/sbtboot"
      - "sbt-cache/target"
      - "sbt-cache/coursier"

  before_script:
    #aws cli requires pip, which requires python, which the image does not have
    - apt-get update
    - apt-get install python3 -y
    - apt-get install python3-pip -y
    - export PATH=~/.local/bin:$PATH
    - pip3 install awscli # Install aws
    - apt-get install zip
    # creating a branch is needed for sbtrelease.Vcs. This is needed because gitlab
    # operates in "detached head" mode
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"

# include all job ci files here:
include:
  - local: 'mlplatform/.gitlab-ci.yml'
  - local: 'plutus/.gitlab-ci.yml'
  - local: 'contextual-features-scala/.gitlab-ci.yml'