apiVersion: v1
kind: Service
metadata:
  name: mlplatform-api-svc
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: mlplatform-api
  type: LoadBalancer
