FROM nvcr.io/nvidia/tensorflow:21.02-tf2-py3


WORKDIR /opt/application/

RUN pip3 install --upgrade pip
RUN pip3 install --quiet --no-cache-dir \
    'tensorflow-probability===0.12.2' \
    'pandas' \
    'tensorflow-serving-api==2.4.0'


COPY ./plutus ./plutus
COPY ./main.py ./

RUN ls && pwd

ENTRYPOINT ["python3", "./main.py"]
