FROM tensorflow/tensorflow:2.4.1


WORKDIR /opt/application/

RUN pip3 install --upgrade pip
RUN pip3 install --quiet --no-cache-dir \
    'tensorflow-probability===0.12.2' \
    'pandas' \
    'tensorflow-serving-api==2.4.1' \
    'prometheus_client' \
    'awscli'


COPY ./plutus ./plutus
COPY ./main.py ./

RUN ls && pwd

ENTRYPOINT ["python3", "./main.py"]
