kind: Deployment
apiVersion: apps/v1
metadata:
  name: mlplatform-api
  namespace: mlplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlplatform-api
  template:
    spec:
      imagePullSecrets:
        - name: use-docker
      containers:
      - name: mlplatform-api
        image: mlplatform-api
        ports:
        - containerPort: 8083
        startupProbe:
          httpGet:
            path: /healthcheck
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 6
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 6
          timeoutSeconds: 5
