package com.thetradedesk.audience.jobs.policytable

import java.time.LocalDate

case class AudiencePolicyTableGeneratorConfig(
  storageCloud: String,
  seedMetaDataRecentVersion: Option[String],
  seedMetadataS3Bucket: String,
  countryDensityThreshold: Double,
  seedMetadataS3Path: String,
  seedRawDataS3Bucket: String,
  seedRawDataS3Path: String,
  seedRawDataRecentVersion: Option[String],
  policyTableResetSyntheticId: Boolean,
  conversionLookBack: Int,
  expiredDays: Int,
  policyTableLookBack: Int,
  policyS3Bucket: String,
  policyS3Path: String,
  maxVersionsToKeep: Int,
  reuseAggregatedSeedIfPossible: Boolean,
  bidImpressionRepartitionNum: Int,
  seedRepartitionNum: Int,
  bidImpressionLookBack: Int,
  graphUniqueCountKeepThreshold: Int,
  graphScoreThreshold: Double,
  seedJobParallel: Int,
  seedProcessLowerThreshold: Long,
  seedProcessUpperThreshold: Long,
  ttdOwnDataUpperThreshold: Long,
  seedExtendGraphUpperThreshold: Long,
  activeUserRatio: Double,
  aemPixelLimit: Int,
  selectedPixelsConfigPath: String,
  useSelectedPixel: Boolean,
  campaignFlightStartingBufferInDays: Int,
  allRSMSeed: Boolean,
  audioGraphExtensionRatio: Double,
  ctvGraphExtensionRatio: Double,
  activeAdvertiserLookBackDays: Int,
  newSeedLookBackDays: Int,
  userDownSampleHitPopulation: Int,
  saltToSampleUser: String,
  densityFeatureScoreNewSeedPrefix: String,
  readSeedDetailMode: Boolean,
  runDate: LocalDate
)
