package com.thetradedesk.geronimo.shared.schemas

case class AdvertiserRecord(AdvertiserId: String,
                            AdvertiserIdInteger: Long,
                            PartnerId: String,
                            AdvertiserName: String,
                            AdvertiserDescription: Option[String],
                            CurrencyCodeId: String,
                            ContactId: Option[String],
                            PaymentMethodTypeId: Int,
                            AttributionClickLookbackWindowInSeconds: Int,
                            AttributionImpressionLookbackWindowInSeconds: Int,
                            ClickDedupeWindowInSeconds: Int,
                            ConversionDeDupeWindowInSeconds: Int,
                            RightMediaDefaultOfferTypeId: Option[BigInt],
                            RecencyBucketListId: String,
                            CreatedAt: java.sql.Timestamp,
                            LastUpdatedAt: java.sql.Timestamp,
                            IsVisible: Boolean,
                            AdvertiserFacebookAccountId: Option[BigInt],
                            FacebookAdAccountId: Option[BigInt],
                            ManagerId: Option[String],
                            BuyerId: Option[String],
                            MaximumNumberOfIpRanges: Int,
                            MaximumNumberOfSiteListLines: Int,
                            IndustryCategoryId: Option[BigInt],
                            ExcludeFromReporting: Boolean,
                            PrimaryAttributionCluster: Option[Int],
                            DailyConversionLimit: Option[BigInt],
                            SecondaryAttributionCluster: Option[Int],
                            AdvertiserRevenueGroupId: String,
                            HasLogo: Boolean,
                            MaximumNumberOfTemperatureAdjustmentsPerAdGroup: Int,
                            DefaultAdGroupTemperatureBucketListId: Int,
                            ReportingTemperatureBucketListId: Int,
                            WitholdTTDMarginFromAdvertiserCostOverride: Option[Boolean],
                            IncludeTTDMarginInAdvertiserCost: Boolean,
                            BaiduIndustryCategoryId: Option[BigInt],
                            InvoiceTimeZoneId: Option[Int],
                            UseMediaCostBasisForCampaignFees: Boolean,
                            OverridePartnerDefaultImpressionTrackingUrl: Boolean,
                            OverridePartnerDefaultImpressionTrackingUrl2: Boolean,
                            OverridePartnerDefaultImpressionTrackingUrl3: Boolean,
                            DefaultThirdPartyImpressionTrackingUrl: Option[String],
                            DefaultThirdPartyImpressionTrackingUrl2: Option[String],
                            DefaultThirdPartyImpressionTrackingUrl3: Option[String],
                            AdsTxtSiteUnauthorizedHandlingOverrideId: Int,
                            AdvertiserLegalName: Option[String],
                            AdvertiserBrandName: Option[String],
                            IsGdprWhitelisted: Boolean,
                            DontUsePreGdprFirstPartyData: Option[Boolean],
                            AdvertiserCorporationId: Option[String])

object AdvertiserDataset {

  val ADVS3 = f"s3://thetradedesk-useast-qubole/warehouse.external/thetradedesk.db/provisioning/advertiser/v=1"

}
