
variables:
  PLUTUS_JAR_NAME: "plutus.jar"
  FEATURES_JSON: "features.json"
  PLUTUS_MERGEREQUESTS_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/plutus/jars/mergerequests"
  PLUTUS_SNAPSHOTS_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/plutus/jars/snapshots"
  PLUTUS_PROD_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/plutus/jars/prod"
  PLUTUS_ASSEMBLY_OUT: "$CI_PROJECT_DIR/plutus/target/scala-2.12/plutus.jar"
  PLUTUS_FEATURES_DEST: "s3://thetradedesk-mlplatform-us-east-1/libs/plutus/features/"
  PLUTUS_MERGEREQUESTS_SCRIPTS_DEST: "s3://thetradedesk-mlplatform-us-east-1/libs/plutus/scripts/mergerequests/$CI_COMMIT_REF_SLUG/"
  SCALA_BUILD_IMAGE_2_13_0: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"

plutus:test:
  image: "$SCALA_BUILD_IMAGE_2_13_0"
  stage: test
  cache:
    policy: pull
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "plutus/**/*"
        - "plutus/build.sbt"
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "plutus/**/*"
        - "plutus/build.sbt"
  before_script:
    # we don't need to set up the machine for S3 in order to run tests
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  script: 
    - pushd ./plutus/
    - sbt test
    - popd
    - echo "ran plutus_test"

plutus:push_bits_merge_request:
  image: "$SCALA_BUILD_IMAGE_2_13_0"
  stage: assembly_upload
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "plutus/src/**/*"
  script:
    - pushd ./plutus/
    - sbt "set test in assembly := {}" clean assembly
    - DEST=${PLUTUS_MERGEREQUESTS_JAR_FOLDER}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - aws s3 cp ${PLUTUS_ASSEMBLY_OUT} ${DEST}/${PLUTUS_JAR_NAME}
    - popd
    - echo "ran plutus_push_bits_merge_request"

plutus:push_bits_master_snapshot:
  image: "$SCALA_BUILD_IMAGE_2_13_0"
  stage: assembly_upload
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "plutus/src/**/*"
        - "plutus/build.sbt"
  script:
    - pushd ./plutus/
    - sbt "set test in assembly := {}" clean assembly
    - DEST=${PLUTUS_SNAPSHOTS_JAR_FOLDER}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - aws s3 cp ${PLUTUS_ASSEMBLY_OUT} ${DEST}/${PLUTUS_JAR_NAME}
    - popd
    - echo "ran plutus_push_bits_master_snapshot"

plutus:deploy_release:
  image: "$SCALA_BUILD_IMAGE_2_13_0"
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "plutus/src/**/*"
      allow_failure: false
  script:
    - pushd ./plutus/
    - sbt "set test in assembly := {}" clean assembly
    - aws s3 cp ${PLUTUS_ASSEMBLY_OUT} ${PLUTUS_PROD_JAR_FOLDER}/${PLUTUS_JAR_NAME}
    - popd
    - echo "ran plutus_deploy_release"
