plutus_test:
  image: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"
  stage: test
  cache:
    policy: pull
#  before_script:
#    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  script: 
      - sbt test
      - echo "ran plutus_test"

plutus_push_bits_merge_request:
  image: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"
  stage: assembly_upload
  needs: []
  except:
    - master
    - /^release-\d{4}\.\d{2}\.\d{2}$/
  script:
    - echo "ran plutus_push_bits_merge_request"

plutus_push_bits_master_snapshot:
  image: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"
  stage: assembly_upload
  only:
    - master
  script:
    - echo "ran plutus_push_bits_master_snapshot"

plutus_push_bits_release:
  image: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"
  stage: assembly_upload
  only:
    - /^release-\d{4}\.\d{2}\.\d{2}$/
  script:
    - echo "ran plutus_push_bits_release"

plutus_deploy_release:
  image: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"
  stage: deploy
  only:
    - /^release-\d{4}\.\d{2}\.\d{2}$/
  when: manual
  allow_failure: false
  script:
    - echo "ran plutus_deploy_release"
