/** MACHINE-GENERATED FROM AVRO SCHEMA. DO NOT EDIT DIRECTLY */
package com.ttd.contextual.util.elDoradoUtilities.streaming.records.rtb.bidfeedback

import com.ttd.contextual.util.elDoradoUtilities.streaming.records.rtb.{AdsTxtSellerTypeLookupRecord, BrowserLookupRecord, DataUsageRecord, DealOriginAndTypeLookupRecord, DeviceTypeLookupRecord, FeeFeatureAdjustmentContext, FeeFeatureUsageLogBackingData, OSFamilyLookupRecord, PredictiveClearingModeLookupRecord, SkippabilityConstraintLookupRecord, SupplyChainScoringCodeLookupRecord, VideoPlaybackTypeLookupRecord}
import com.ttd.contextual.util.elDoradoUtilities.streaming.records.rtb.{AdsTxtSellerTypeLookupRecord, BrowserLookupRecord, DataUsageRecord, DealOriginAndTypeLookupRecord, DeviceTypeLookupRecord, FeeFeatureAdjustmentContext, FeeFeatureUsageLogBackingData, OSFamilyLookupRecord, OSLookupRecord, PredictiveClearingModeLookupRecord, RenderingContextLookupRecord, SkippabilityConstraintLookupRecord, SupplyChainScoringCodeLookupRecord, VideoPlaybackTypeLookupRecord}

case class BidFeedbackRecordV4(GroupId: String = "",
                               LogEntryTime: java.sql.Timestamp,
                               HandlingDurationInTicks: Long,
                               BidFeedbackId: String,
                               AdId: Option[String],
                               BidRequestId: String,
                               MediaCostCPMInUSD: Option[BigDecimal],
                               SupplyVendor: Option[String],
                               PartnerId: Option[String],
                               AdvertiserId: Option[String],
                               CampaignId: Option[String],
                               AdGroupId: Option[String],
                               ChannelId: Option[String],
                               CreativeId: Option[String],
                               AdWidthInPixels: Option[Int],
                               AdHeightInPixels: Option[Int],
                               Frequency: Long,
                               RawUrl: Option[String],
                               IsWinningPriceValid: Boolean,
                               FeedbackSentTime: Option[java.sql.Timestamp],
                               Site: Option[String],
                               TDID: String,
                               ReferrerCategories: Seq[String],
                               MatchedCategory: Option[String],
                               MatchedSiteFragment: Option[String],
                               MatchedFoldPosition: Int,
                               MatchedSiteStrategyLineId: Option[String],
                               MatchedFoldStrategyLineId: Option[String],
                               UserHourOfWeek: Option[Int],
                               AdGroupSelectionAlgorithmConfigHash: Option[String],
                               Country: Option[String],
                               Region: Option[String],
                               Metro: Option[String],
                               City: Option[String],
                               DiscrepancyAdjustmentMultiplier: Option[BigDecimal],
                               IPAddress: Option[String],
                               UserAgent: Option[String],
                               DataUsageRecord: Option[DataUsageRecord],
                               SupplyVendorBillsTTD: Boolean,
                               DeviceType: Option[DeviceTypeLookupRecord],
                               OperatingSystemFamily: Option[OSFamilyLookupRecord],
                               OperatingSystem: Option[OSLookupRecord],
                               Browser: Option[BrowserLookupRecord],
                               PartnerRequestData: Option[String],
                               SupplyVendorPublisherId: Option[String],
                               FeeFeaturesCost: BigDecimal,
                               ReferrerUrl: Option[String],
                               RequestLanguageCodes: Option[String],
                               MatchedLanguageCode: Option[String],
                               FeeFeatureAmounts: Map[String, BigDecimal],
                               DealId: Option[String],
                               FeedbackStatus: Int,
                               FeedbackAgeInMinutes: Long,
                               PrivateContractId: Option[String],
                               TTDCostInUSD: BigDecimal,
                               PartnerCostInUSD: BigDecimal,
                               AdvertiserCostInUSD: BigDecimal,
                               PartnerCurrencyExchangeRateFromUSD: BigDecimal,
                               AdvertiserCurrencyExchangeRateFromUSD: BigDecimal,
                               CampaignVersion: Option[String],
                               FeeSheetVersion: Option[String],
                               TDIDCookieStatus: Option[Int],
                               AdGroupLifetimeFrequency: Long,
                               GRPReportingTargetingIds: Seq[Long],
                               GRPGeoSegmentId: Option[String],
                               FeeFeaturesApplicableContexts: Map[String, FeeFeatureAdjustmentContext],
                               WinningPriceCPMInCurrency: BigDecimal,
                               WinningPriceCurrencyCode: Option[String],
                               CurrencyExchangeRateCheckpoint: Option[java.sql.Timestamp],
                               RenderingContext: Option[RenderingContextLookupRecord],
                               TDIDUsedForBidding: Option[String],
                               DeviceAdvertisingId: Option[String],
                               Latitude: Option[Double],
                               Longitude: Option[Double],
                               TemperatureInCelsius: Option[Double],
                               TemperatureBucketStartInCelsius: Option[Double],
                               TemperatureBucketEndInCelsius: Option[Double],
                               Zip: Option[String],
                               OpenStatId: Option[String],
                               OpenStatIdVersion: Option[String],
                               FactualProximityMatchedDesignId: Option[Int],
                               FactualProximityMatchedTargetingCodeId: Option[Int],
                               DeviceMake: Option[String],
                               DeviceModel: Option[String],
                               TestId: Option[String],
                               CarrierId: Option[Int],
                               NielsenDemoSamplingCampaignId: Option[String],
                               NielsenDemoSamplingSiteId: Option[String],
                               CampaignFlightId: Option[Long],
                               TTDMarginInUSD: Option[BigDecimal],
                               FeeFeatureUsage: Option[Seq[FeeFeatureUsageLogBackingData]],
                               ProvisionalFeedback: Boolean,
                               VideoPlaybackType: Option[VideoPlaybackTypeLookupRecord],
                               SupplyVendorSkippabilityConstraint: Option[SkippabilityConstraintLookupRecord],
                               DealWinningPriceAdjustment: BigDecimal,
                               Signature: Option[String],
                               SubmittedBidAmountInUSD: BigDecimal,
                               PartnerCurrency: Option[String],
                               AdvertiserCurrency: Option[String],
                               AdapterId: Option[String],
                               NativePlacementTypeId: Option[Int],
                               ImpressionSecondsFromEpoch: Long,
                               ImpressionPlacementId: Option[String],
                               AdsTxtSellerType: Option[AdsTxtSellerTypeLookupRecord],
                               CurrencyBufferCostInUSDollars: Option[BigDecimal],
                               IsManagedByTTD: Option[Boolean],
                               FirstPriceAdjustment: Option[BigDecimal],
                               StreamingMediaNetwork: Option[String],
                               StreamingMediaChannel: Option[String],
                               IsGdprApplicable: Boolean = false,
                               TTDHasConsentForDataSegmenting: Boolean = false,
                               PartnerHasConsent: Boolean = false,
                               VolumeControlPriority: Option[Int] = None,
                               PredictiveClearingMode: Option[PredictiveClearingModeLookupRecord] = None,
                               HouseholdAnchor: Option[String] = None,
                               PreventPrivacyIconFee: Boolean = false,
                               PrivateContractOwningPartnerId: Option[String] = None,
                               PrivateContractOwningPartnerCurrencyCodeId: Option[String] = None,
                               PrivateContractOwningPartnerCurrencyExchangeRate: Option[BigDecimal] = None,
                               ContextualMetadataHash: Option[Long] = None,
                               SSPAuctionId: Option[String] = None,
                               PredictiveClearingRandomControl: Boolean = false,
                               TDIDExternal: Option[String] = None,
                               DeviceAdvertisingIdExternal: Option[String] = None,
                               IPAddressExternal: Option[String] = None,
                               LatitudeExternal: Option[Double] = None,
                               LongitudeExternal: Option[Double] = None,
                               ZipExternal: Option[String] = None,
                               ImpressionMultiplier: Option[BigDecimal] = None,
                               WhiteOpsPixelSent: Option[Boolean] = None,
                               SupplyChainScoringCode: Option[SupplyChainScoringCodeLookupRecord] = None,
                               AuctionType: Option[String] = None,
                               ProvisionalFeedbackExpirySeconds: Option[Int] = None,
                               DealOriginAndType: Option[DealOriginAndTypeLookupRecord] = None,
                               ReferrerGenresList: Option[Seq[String]] = None,
                               MatchedGenre: Option[String] = None,
                               CustomBidderTrackingId: Option[String] = None,
                               ContentDuration: Option[String] = None,
                               LiveStream: Option[Boolean] = None,
                               IsCcpaApplicable: Option[Boolean] = None,
                               UserOptedOutOfDataSale: Option[Boolean] = None,
                               BrowserTDID: Option[String] = None,
                               IsMeasurable: Option[Boolean] = None,
                               FeedbackBidderCacheMachineName: Option[String] = None,
                               WeatherCondition: Option[Int] = None,
                               HashedIpAsUiid: Option[String] = None
                              )