package com.ttd.contextual.util.elDoradoUtilities.streaming.records.rtb

case class FeeFeatureAdjustmentPredictiveCleaningContext(AdjustmentOperationType: FeeFeatureAdjustmentOperationTypeLookupRecord, FirstPriceAdjustment: BigDecimal, PredictiveClearingMode: PredictiveClearingModeLookupRecord, SubmittedBidInUSD: BigDecimal)
