package com.ttd.contextual.util.elDoradoUtilities.streaming.records.rtb

case class FeeFeatureAdjustmentImpressionCountSamplingContext(AdjustmentOperationType: FeeFeatureAdjustmentOperationTypeLookupRecord, SamplingRate: BigDecimal)
