include: '/.ci-templates/common.yml'

variables:
  SCALA_BUILD_IMAGE_2_13_0: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"
  GERONIMO_JAR_NAME: "geronimo.jar"
  GERONIMO_MERGEREQUESTS_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/geronimo/jars/mergerequests"
  GERONIMO_SNAPSHOTS_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/geronimo/jars/snapshots"
  GERONIMO_PROD_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/geronimo/jars/prod"
  GERONIMO_ASSEMBLY_OUT: "/builds/thetradedesk/mlplatform/geronimo/target/scala-2.12/geronimo.jar"



geronimo:test:
  image: "$SCALA_BUILD_IMAGE_2_13_0"
  stage: test
  cache:
    policy: pull
  rules:
    - !reference [.commonRuleConditions, isMR]
    - changes:
        - "geronimo/src/**/*"
    - !reference [.commonRuleConditions, isDefaultBranch] 
    - changes:
        - "geronimo/src/**/*"
  before_script:
    # we don't need to set up the machine for S3 in order to run tests
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  script:
    - pushd ./geronimo/
    - sbt test
    - popd
    - echo "ran geronimo_test"


geronimo:push_bits_merge_request:
  image: "$SCALA_BUILD_IMAGE_2_13_0"
  stage: assembly_upload
  rules:
    - !reference [.commonRuleConditions, isMR]
    - changes:
        - "geronimo/src/**/*"
  script:
    - NEXUS_MAVEN_READ_USER=${NEXUS_MAVEN_SNAPSHOT_USER}
    - NEXUS_MAVEN_READ_PASS=${NEXUS_MAVEN_SNAPSHOT_PASS}
    - pushd ./geronimo/
    - sbt "set test in assembly := {}" clean assembly
    - DEST=${GERONIMO_MERGEREQUESTS_JAR_FOLDER}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - aws s3 cp ${GERONIMO_ASSEMBLY_OUT} ${DEST}/${GERONIMO_JAR_NAME}
    - sbt +publish
    - popd
    - echo "ran GERONIMO_push_bits_merge_request"

geronimo:push_bits_master_snapshot:
  image: "$SCALA_BUILD_IMAGE_2_13_0"
  stage: assembly_upload
  rules:
    - !reference [.commonRuleConditions, isDefaultBranch] 
    - changes:
        - "geronimo/src/**/*"
  script:
    - pushd ./geronimo/
    - sbt "set test in assembly := {}" clean assembly
    - DEST=${GERONIMO_SNAPSHOTS_JAR_FOLDER}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - aws s3 cp ${GERONIMO_ASSEMBLY_OUT} ${DEST}/${GERONIMO_JAR_NAME}
    - popd
    - echo "ran geronimo_push_bits_master_snapshot"

geronimo:deploy_release:
  image: "$SCALA_BUILD_IMAGE_2_13_0"
  stage: deploy
  rules:
    - !reference [.commonRuleConditions, isDefaultBranch] 
    - changes:
        - "geronimo/src/**/*"
      when: manual
      allow_failure: false
  script:
    - NEXUS_MAVEN_READ_USER=${NEXUS_MAVEN_RELEASE_USER}
    - NEXUS_MAVEN_READ_PASS=${NEXUS_MAVEN_RELEASE_PASS}
    - echo "Nexus user is ${NEXUS_READ_USER}"
    - pushd ./geronimo/
    - sbt +publish
    - sbt "set test in assembly := {}" clean assembly
    - aws s3 cp ${GERONIMO_ASSEMBLY_OUT} ${GERONIMO_PROD_JAR_FOLDER}/${GERONIMO_JAR_NAME}
    - popd
    - echo "ran geronimo_deploy_release"

