package com.ttd.ml.util.elDoradoUtilities.streaming.records.rtb

case class FeeFeatureAdjustmentImpressionCountSamplingContext(AdjustmentOperationType: FeeFeatureAdjustmentOperationTypeLookupRecord, SamplingRate: BigDecimal)
