apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  ports:
    - port: 1433
      $patch: delete # https://github.com/kubernetes-sigs/kustomize/issues/173
    - name: main
      port: 1436
      targetPort: 1433

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  template:
    spec:
      containers:
        - name: mssql
          env:
            - name: SA_PASSWORD
              value: "{{Config.Get `Databases:MLPlatform:Password` }}"
