variables:
  MLPLATFORM_COMMON_ASSEMBLY_OUT: "common/target/mlplatform-common.jar"
  MLPLATFORM_COMMON_JAR_NAME: "mlplatform-common.jar"
  
  MLPLATFORM_FEATURESTORE_ASSEMBLY_OUT: "fsclient/target/mlplatform-fsclient.jar"
  MLPLATFORM_FEATURESTORE_JAR_NAME: "mlplatform-fsclient.jar"
    
  MLPLATFORM_API_ASSEMBLY_OUT: "api/target/mlplatform-api.jar"
  MLPLATFORM_API_JAR_NAME: "mlplatform-api.jar"
    
  MLPLATFORM_MERGEREQUESTS_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/mlplatform/jars/mergerequests"
  MLPLATFORM_SNAPSHOTS_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/mlplatform/jars/snapshots"
  MLPLATFORM_PROD_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/mlplatform/jars/prod"
  

mlplatform:test:
  image: "$MAVEN_BUILD_IMAGE"
  stage: test
  cache:
    policy: pull
  only:
    changes:
      - "mlplatform/**/*"
  before_script:
    # we don't need to set up the machine for S3 in order to run tests
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  script: 
    - pushd ./mlplatform/
    - mvn test
    - popd
    - echo "ran mlplatform_test"

mlplatform:push_bits_merge_request:
  image: "$MAVEN_BUILD_IMAGE"
  stage: assembly_upload
  artifacts:
    untracked: true
  except:
    refs:
      - master
  only:
    changes:
      - "mlplatform/**/*"
  script:
    - pushd ./mlplatform/
    - mvn -Dmaven.test.skip=true package
    - DEST=${MLPLATFORM_MERGEREQUESTS_JAR_FOLDER}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - aws s3 cp ${MLPLATFORM_COMMON_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_COMMON_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_FEATURESTORE_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_FEATURESTORE_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_API_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_API_JAR_NAME}
    - popd
    - echo "ran mlplatform_push_bits_merge_request"

mlplatform:push_bits_master_snapshot:
  image: "$MAVEN_BUILD_IMAGE"
  stage: assembly_upload
  artifacts:
    untracked: true
  only:
    refs:
      - master
    changes:
      - "mlplatform/**/*"
  script:
    - pushd ./mlplatform/
    - mvn -Dmaven.test.skip=true package
    - DEST=${MLPLATFORM_SNAPSHOTS_JAR_FOLDER}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - aws s3 cp ${MLPLATFORM_COMMON_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_COMMON_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_FEATURESTORE_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_FEATURESTORE_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_API_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_API_JAR_NAME}
    - popd
    - echo "ran mlplatform_push_bits_master_snapshot"

mlplatform:deploy_api_docker_image_merge_request:
  image: proxy.docker.adsrvr.org/docker:git
  stage: deploy
  dependencies: 
    - mlplatform:push_bits_merge_request
  except:
    refs:
      - master
  services:
    - docker:dind
  after_script:
    - docker logout ${DOCKER_PRODUCTION_REGISTRY}
    - docker logout ${DOCKER_DEV_REGISTRY}
  only:
    changes:
      - "mlplatform/**/*"
  before_script:
    # override the default before script
    # we don't need to set up the machine for S3 in order to build and push the docker image
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  script:
    - cd ./mlplatform/api
    - echo "logging in to ${DOCKER_DEV_REGISTRY}"
    - docker login ${DOCKER_DEV_REGISTRY} -u ${DOCKER_DEV_USER} -p ${DOCKER_DEV_PASS}
    - docker build -t ${DOCKER_DEV_REGISTRY}/mlplatform-api:${CI_COMMIT_SHORT_SHA} -t ${DOCKER_DEV_REGISTRY}/mlplatform-api:latest .
    - docker push ${DOCKER_DEV_REGISTRY}/mlplatform-api:${CI_COMMIT_SHORT_SHA}
    - sed -i "s/_DOCKER_REGISTRY_/$DOCKER_DEV_REGISTRY/g" ./k8s/mlplatform-api-deployment.yaml
    - sed -i "s/_DOCKER_IMAGE_/$CI_COMMIT_SHORT_SHA/g" ./k8s/mlplatform-api-deployment.yaml
    - echo "ran deploy_api_merge_request"
    
mplatform:deploy_api_k8s_merge_request:
  image: lwolf/helm-kubectl-docker:latest
  stage: k8s_deploy
  dependencies: 
    - mlplatform:deploy_api_docker_image_merge_request
  except:
    refs:
      - master
  before_script:
    - mkdir -p /root/.kube
    - apk add --no-cache curl openssl
  script:
    # set kubectl config
    - cd ./mlplatform/api
    - kubectl config set-cluster general-use-non-production --server $EKS_NON_PROD_URL
    - kubectl config set clusters.general-use-non-production.certificate-authority-data $EKS_NON_PROD_CRT
    - kubectl config set-credentials $EKS_NON_PROD_USER --token="$EKS_NON_PROD_TOKEN"
    - kubectl config set-context general-use-non-production --cluster=general-use-non-production --namespace mlplatform --user=$EKS_NON_PROD_USER
    - kubectl config use-context general-use-non-production
#    - kubectl get pods
    - kubectl apply -n mlplatform -f ./k8s/mlplatform-api-deployment.yaml

mlplatform:deploy_release:
  image: "$MAVEN_BUILD_IMAGE"
  stage: deploy
  when: manual
  only:
    refs:
      - master
    changes:
      - "mlplatform/**/*"
  allow_failure: false
  script:
    - pushd ./mlplatform/
    - mvn -Dmaven.test.skip=true package
    - aws s3 cp ${ASSEMBLY_OUT} ${MLPLATFORM_PROD_JAR_FOLDER}/${MLPLATFORM_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_COMMON_ASSEMBLY_OUT} ${MLPLATFORM_PROD_JAR_FOLDER}/${MLPLATFORM_COMMON_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_FEATURESTORE_ASSEMBLY_OUT} ${MLPLATFORM_PROD_JAR_FOLDER}/${MLPLATFORM_FEATURESTORE_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_API_ASSEMBLY_OUT} ${MLPLATFORM_PROD_JAR_FOLDER}/${MLPLATFORM_API_JAR_NAME}
    - popd
    - echo "ran mlplatform_deploy_release"
