variables:
  MLPLATFORM_COMMON_ASSEMBLY_OUT: "common/target/mlplatform-common.jar"
  MLPLATFORM_COMMON_JAR_NAME: "mlplatform-common.jar"

  MLPLATFORM_FEATURESTORE_ASSEMBLY_OUT: "fsclient/target/mlplatform-fsclient.jar"
  MLPLATFORM_FEATURESTORE_JAR_NAME: "mlplatform-fsclient.jar"

  MLPLATFORM_API_ASSEMBLY_OUT: "api/target/mlplatform-api.jar"
  MLPLATFORM_API_JAR_NAME: "mlplatform-api.jar"

  MLPLATFORM_MERGEREQUESTS_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/mlplatform/jars/mergerequests"
  MLPLATFORM_SNAPSHOTS_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/mlplatform/jars/snapshots"
  MLPLATFORM_PROD_JAR_FOLDER: "s3://thetradedesk-mlplatform-us-east-1/libs/mlplatform/jars/prod"

  MLPLATFORM_MAVEN_BUILD_IMAGE: "maven:3.8.1-jdk-8"

  #This workflow rule will prevent duplicate pipelines for merge request AND branch commits
  #BUT we should avoid defining workflow rules on the top level (repo) .gitlab-ci/yml because it seems to
  # have weird interactions with inherited job rules from each project
  #   If the pipeline is triggered by:
  #
  #   A merge request, run a merge request pipeline. For example, a merge request pipeline can be triggered by a push to a branch with an associated open merge request.
  #   A change to a branch, but a merge request is open for that branch, do not run a branch pipeline.
  #   A change to a branch, but without any open merge requests, run a branch pipeline.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

mlplatform:test:
  image: "$MLPLATFORM_MAVEN_BUILD_IMAGE"
  stage: test
  cache:
    policy: pull
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "mlplatform/**/*"
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - "mlplatform/**/*"
  before_script:
    # we don't need to set up the machine for S3 in order to run tests
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  script:
    - pushd ./mlplatform/
    - mvn test
    - popd
    - echo "ran mlplatform_test"

mlplatform:push_bits_merge_request:
  image: "$MLPLATFORM_MAVEN_BUILD_IMAGE"
  stage: assembly_upload
  artifacts:
    untracked: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "mlplatform/**/*"
  script:
    - pushd ./mlplatform/
    - mvn -Dmaven.test.skip=true package
    - DEST=${MLPLATFORM_MERGEREQUESTS_JAR_FOLDER}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - aws s3 cp ${MLPLATFORM_COMMON_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_COMMON_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_FEATURESTORE_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_FEATURESTORE_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_API_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_API_JAR_NAME}
    - popd
    - echo "ran mlplatform_push_bits_merge_request"

mlplatform:push_bits_master_snapshot:
  image: "$MLPLATFORM_MAVEN_BUILD_IMAGE"
  stage: assembly_upload
  artifacts:
    untracked: true
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - "mlplatform/**/*"
  script:
    - pushd ./mlplatform/
    - mvn -Dmaven.test.skip=true package
    - DEST=${MLPLATFORM_SNAPSHOTS_JAR_FOLDER}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - aws s3 cp ${MLPLATFORM_COMMON_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_COMMON_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_FEATURESTORE_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_FEATURESTORE_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_API_ASSEMBLY_OUT} ${DEST}/${MLPLATFORM_API_JAR_NAME}
    - popd
    - echo "ran mlplatform_push_bits_master_snapshot"

mlplatform:deploy_api_dev_docker_image_merge_request:
  image: proxy.docker.adsrvr.org/docker:git
  stage: deploy
  dependencies:
    - mlplatform:push_bits_merge_request
  artifacts:
    paths:
      - mlplatform/api/target/mlplatform-api-deployment.yaml
  services:
    - docker:dind
  after_script:
    - docker logout ${DOCKER_PRODUCTION_REGISTRY}
    - docker logout ${DOCKER_DEV_REGISTRY}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "mlplatform/**/Dockerfile"
  before_script:
    # override the default before script
    # we don't need to set up the machine for S3 in order to build and push the docker image
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  script:
    - cd ./mlplatform/api
    - echo "logging in to ${DOCKER_DEV_REGISTRY}"
    - docker login ${DOCKER_DEV_REGISTRY} -u ${DOCKER_DEV_USER} -p ${DOCKER_DEV_PASS}
    - docker build -t ${DOCKER_DEV_REGISTRY}/mlplatform-api:${CI_COMMIT_SHORT_SHA} -t ${DOCKER_DEV_REGISTRY}/mlplatform-api:latest .
    - docker push ${DOCKER_DEV_REGISTRY}/mlplatform-api:${CI_COMMIT_SHORT_SHA}
    - cp ./k8s/mlplatform-api-deployment.yaml ./target/mlplatform-api-deployment.yaml
    - sed -i "s/_DOCKER_REGISTRY_/$DOCKER_DEV_REGISTRY/g" ./target/mlplatform-api-deployment.yaml
    - sed -i "s/_DOCKER_IMAGE_/$CI_COMMIT_SHORT_SHA/g" ./target/mlplatform-api-deployment.yaml
    - echo "ran deploy_api_dev_docker_image_merge_request"

mplatform:deploy_api_dev_k8s_merge_request:
  image: lwolf/helm-kubectl-docker:latest
  stage: k8s_deploy
  dependencies:
    - mlplatform:deploy_api_dev_docker_image_merge_request
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "mlplatform/**/Dockerfile"
      when: manual
  before_script:
    - mkdir -p /root/.kube
    - apk add --no-cache curl openssl
    - kubectl config set clusters.general-use-non-production.certificate-authority-data $EKS_NON_PROD_CRT
    - kubectl config set-credentials $EKS_NON_PROD_USER
    - kubectl config set-context general-use-non-production --cluster=general-use-non-production --user=$EKS_NON_PROD_USER
    - kubectl config use-context general-use-non-production
    - kubectl config set-credentials $EKS_NON_PROD_USER --token=$EKS_NON_PROD_TOKEN
    - kubectl config set-cluster general-use-non-production --server $EKS_NON_PROD_URL
  script:
    # set kubectl config
    - cd ./mlplatform/api
    - kubectl create secret -n mlplatform generic test-db-user-credentials --from-literal password=${MLPLATFORM_TEST_DB_PASSWORD} -o yaml --dry-run | kubectl apply -n mlplatform -f -
    - kubectl create secret -n mlplatform generic test-db-user-credentials --from-literal username=${MLPLATFORM_TEST_DB_USERNAME} -o yaml --dry-run | kubectl apply -n mlplatform -f -
    - kubectl apply -n mlplatform -f ./target/mlplatform-api-deployment.yaml
    - echo "ran deploy_api_dev_k8s_merge_request"

mlplatform:deploy_jar_release:
  image: "$MLPLATFORM_MAVEN_BUILD_IMAGE"
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - "mlplatform/**/*"
      when: manual
  script:
    - pushd ./mlplatform/
    - mvn -Dmaven.test.skip=true package
    - aws s3 cp ${MLPLATFORM_COMMON_ASSEMBLY_OUT} ${MLPLATFORM_PROD_JAR_FOLDER}/${MLPLATFORM_COMMON_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_FEATURESTORE_ASSEMBLY_OUT} ${MLPLATFORM_PROD_JAR_FOLDER}/${MLPLATFORM_FEATURESTORE_JAR_NAME}
    - aws s3 cp ${MLPLATFORM_API_ASSEMBLY_OUT} ${MLPLATFORM_PROD_JAR_FOLDER}/${MLPLATFORM_API_JAR_NAME}
    - popd
    - echo "ran mlplatform_deploy_jar_release"
