name: tensorflow
channels:
  - rapidsai-nightly
  - gpuci
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel  # required by Python notebooks
  - ipython  # required by Python notebooks
  - numpy  # required by PySpark MLlib
  - pandas  # required by PySpark
  - pip
  - python=3.8.10
  - six  # required by PySpark
  - traitlets # required by PySpark
  - nvtabular
  - pyarrow  # required by PySpark
  - pynvml
  - pip:
    - tensorflow-gpu==2.7.0
    - tensorflow_probability==0.15.* # does not have gpu specific package
    - tensorflow-serving-api-gpu==2.7.* # seems to have a gpu specific package https://github.com/tensorflow/serving/blob/c44257b7e0fb294a19422791906b876d3e704fb1/tensorflow_serving/tools/pip_package/setup.py#L51
